### ISSUE TITLE
Popis hrvatskih riječi - pogrešno formatiranje redaka 509725-509727

### ISSUE THREAD

**Issue by mjurekov** [gigaly/rjecnik-hrvatskih-jezika#1]
Pozdrav! Proučavao sam popis hrvatskih riječi i primijetio da mi parsiranje puca na riječi "smještenim", između redaka 509725 i 509727. Prilažem screenshot.

<img width="347" alt="Screenshot 2020-05-31 at 11 29 05" src="https://user-images.githubusercontent.com/6160464/83349045-f5283780-a331-11ea-8252-abaf37a03b86.png">

**Comment by AdrianoSverko** [comment]
Kako se je to resilo?

**Comment by mjurekov** [comment]
@AdrianoSverko popravio sam lokalno u "smještenim smješten  pridjev"

**Comment by gigaly** [comment]
Hvala na upozorenju. Ispravljeno.
